Notes:
- characters are turned to decimal ints because they cant be turned to base 16 ints
- manually added using hexedit one more byte to square sample5 because my program kept reading 10239 bytes only, and I needed 10240 to evenly split

Need to:
- randomize data 
- split into train and test

In [5]:
import numpy as np

In [18]:
shapes = ['sine', 'square','sawtooth','burst']
empty = []
X = np.arange(320).reshape(1,320)
X.shape

(1, 320)

In [29]:
for shape in shapes:
    for i in range(1,6):
        path = 'dataset/%s/sample%s/sample.dat' % (shape, i)
        data = open(path, 'rb').read()
        print(len(data))
        data_list = [val for val in data]
        print(len(data_list))
        print(data[:10])
        temp_array = np.array(data_list)
        temp_array1 = temp_array.reshape(32,320)
        X = np.append(X,temp_array1,axis=0)

10240
10240
b'`\x00\x00\x00\x01`\x00\x00\x00\x00'
10240
10240
b'\x00\x00`\x00p\x00x\x00\x1e\x00'
10240
10240
b'p\x18\x07\x1cxp`a\x0e\x1c'
10240
10240
b'\x0c\x188\x0ec\x1cc\x18G8'
10240
10240
b'T***T ZU*T'


array([[  0,   1,   2, ..., 317, 318, 319],
       [ 96,   0,   0, ...,   0,   0,   0],
       [  0,   0,   1, ...,   0,   0,   0],
       ...,
       [ 85,  42,  84, ...,  85,  40,  64],
       [ 32,  82,   5, ...,  85,  42,  84],
       [ 37,  42,  84, ...,  37,  42,  85]])

In [13]:
1024/4

256.0

In [4]:
original_num_features = 10240
new_num_features = 320

original_num_samples = 20
minisamples_per_sample = original_num_features / new_num_features
new_num_samples = original_num_samples * minisamples_per_sample

In [5]:
print(minisamples_per_sample)
print(new_num_samples)

32.0
640.0


In [34]:
np.empty([0,1024])

array([], shape=(0, 100), dtype=float64)

In [40]:
#splitting into bigger samples 
#10240
shapes = ['sine', 'square','sawtooth','burst']
X = np.empty([0,1024])
#X = np.arange(1024).reshape(1,1024)
X.shape
for shape in shapes:
    for i in range(1,6):
        path = 'dataset/%s/sample%s/sample.dat' % (shape, i)
        data = open(path, 'rb').read()
        data_list = [val for val in data]
        print(len(data_list))
        temp_array = np.array(data_list)
        temp_array1 = temp_array.reshape(10,1024)
        X = np.append(X,temp_array1,axis=0)

print(X.shape) 
#X = np.delete(X, 1, axis=0)
print(X.shape) 
arr = np.array([[1,0,0,0], [0,1,0,0], [0,0,1,0], [0,0,0,1]])
X
Y = np.repeat(arr, 50, axis=0)
print(Y.shape)
data = np.append(X, Y, axis=1)
np.random.shuffle(data)
print(data.shape)
np.savetxt("data_1024.csv", data, delimiter=",")

10240
10240
10240
10240
10240
10240
10240
10240
10240
10240
10240
10240
10240
10240
10240
10240
10240
10240
10240
10240
(200, 1024)
(200, 1024)
(200, 4)
(200, 1028)


In [32]:
X.shape

(641, 320)

In [33]:
X

array([[  0,   1,   2, ..., 317, 318, 319],
       [  6,  68,   2, ...,  32,   4,  48],
       [  4,  32,   4, ...,   4,  48,   4],
       ...,
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0]])

In [34]:
X = np.delete(X, 1, axis=0)

In [35]:
X.shape

(640, 320)

Y is 640x4 matrix 
- [1,0,0,0] for sine
- [0,1,0,0] for square
- [0,0,1,0] for sawtooth
- [0,0,0,1] for burst

In [36]:
arr = np.array([[1,0,0,0], [0,1,0,0], [0,0,1,0], [0,0,0,1]])

In [37]:
Y = np.repeat(arr, 160, axis=0)

In [38]:
Y.shape

(640, 4)

In [39]:
Y

array([[1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       ...,
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1]])

In [40]:
# join x and y to randomize the data and split it
data = np.append(X, Y, axis=1)
data

array([[ 0,  1,  2, ...,  0,  0,  0],
       [ 4, 32,  4, ...,  0,  0,  0],
       [48,  4, 32, ...,  0,  0,  0],
       ...,
       [ 0,  0,  0, ...,  0,  0,  1],
       [ 0,  0,  0, ...,  0,  0,  1],
       [ 0,  0,  0, ...,  0,  0,  1]])

In [41]:
data.shape

(640, 324)

In [42]:
#shuffle the array
np.random.shuffle(data)

In [43]:
data

array([[ 0,  0,  0, ...,  0,  0,  1],
       [ 0,  0,  0, ...,  1,  0,  0],
       [14, 30, 60, ...,  1,  0,  0],
       ...,
       [ 1,  3,  2, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  1],
       [48, 96, 64, ...,  0,  0,  0]])

In [44]:
data.shape

(640, 324)

In [45]:
np.savetxt("full_data.csv", data, delimiter=",")

<h3> Separate into train and test
- 448 train
- 192 test

In [242]:
X_train = data[:448,:320]

In [243]:
X_train.shape

(448, 320)

In [244]:
y_train = data[:448,320:]

In [245]:
y_train.shape

(448, 4)

In [246]:
X_test = data[448:,:320]

In [247]:
X_test.shape

(192, 320)

In [248]:
y_test = data[448:,320:]

In [249]:
y_test.shape

(192, 4)

Neural network with 3 layers, input, hidden and output
- num of training examples m -> 448
- num of hidden layer activations -> 100

- input layer has 320 activations + 1 (m x input_layer_size+1 matrix)
- hidden layer has 101 activations + 1(m x hidden_layer_size+1 matrix)
- output layer has 4 nodes (m x num_labels matrix)

2 theta matrices needed:
- theta1 -> hidden_layer_size x input_layer_size+1
- theta2 -> num_labels x hidden_layer_size+1

In [250]:
m = X_train.shape[0]
input_layer_size = 320
hidden_layer_size = 100
num_labels = 4

Thetas

In [251]:
init_epsilon = 0.12

In [252]:
theta1 = np.random.rand(hidden_layer_size,input_layer_size+1) * (2*init_epsilon) - init_epsilon
theta1.shape

(100, 321)

In [253]:
theta2 = np.random.rand(num_labels,hidden_layer_size+1) * (2*init_epsilon) - init_epsilon
theta2.shape

(4, 101)

Add column of 1s to X_train

In [254]:
ones_col = np.ones((m,1))

In [255]:
X_train = np.append(ones_col, X_train, axis=1)

In [256]:
X_train

array([[  1.,   0.,   1., ...,   0., 120.,   0.],
       [  1.,   3.,   7., ...,   7.,  15.,  14.],
       [  1.,   0.,   0., ...,  62.,   0.,   0.],
       ...,
       [  1.,   4.,  12., ...,   2.,   4.,   4.],
       [  1.,  72.,  72., ...,  64.,  64.,  72.],
       [  1.,   0.,   0., ...,   0.,   0.,   0.]])

<h3> Hypothesis and forward prop

In [257]:
#basic rundown of just one layer
hidden = np.dot(X_train,np.transpose(theta1))


In [258]:
#hidden layer
hidden.shape

(448, 100)

In [259]:
#add column of ones to the hidden layer
hidden = np.append(ones_col, hidden, axis=1)
hidden.shape

(448, 101)

In [260]:
output = np.dot(hidden,np.transpose(theta2))

In [261]:
output.shape

(448, 4)

In [262]:
#sine
output[0]

array([ 29.73654243,  -9.36445717, -29.82487768, -10.91752918])

In [263]:
def sigmoid(arr):
    # 1 / (1 + exp(-z))
    sig = 1 / (1 + np.exp(np.negative(arr)))
    return sig

<h3> Hypothesis and forward prop with sigmoid

In [264]:
hidden = np.dot(X_train,np.transpose(theta1))
hidden = np.append(ones_col, hidden, axis=1)
hidden = sigmoid(hidden)
output = np.dot(hidden,np.transpose(theta2))
output = sigmoid(output)

In [265]:
output[0]

array([0.64235825, 0.52366222, 0.63350385, 0.65419898])

In [266]:
def forward_prop(theta1, theta2, X):
    hidden = np.dot(X,np.transpose(theta1))
    hidden = np.append(ones_col, hidden, axis=1)
    hidden = sigmoid(hidden)
    output = np.dot(hidden,np.transpose(theta2))
    output = sigmoid(output)
    return output

In [267]:
forward_prop(theta1, theta2, X_train)

array([[0.64235825, 0.52366222, 0.63350385, 0.65419898],
       [0.67416087, 0.57001225, 0.50466792, 0.63475979],
       [0.47020368, 0.37344518, 0.57199762, 0.55411363],
       ...,
       [0.67499164, 0.60886606, 0.54781566, 0.69564552],
       [0.65609351, 0.59125228, 0.53338294, 0.57907371],
       [0.61083775, 0.60535628, 0.70857199, 0.76385713]])

In [268]:
y_train[0]

array([0, 0, 1, 0])

<h3> Backward prop

In [ ]:
#first the cost function to compute the error